info:
    app-name: storescp
#logging:
#    file: logs/storescp.log
storescp:
    device-name: testscp
    port: 11117
    storage-dir: delete/storescp #set to /temp after testing
    clear-storage-directory-on-start: true #warning - will delete all contents of storage directory
    storage-bucket: my-dicom-upload
    storage-bucket-region: us-east-1
    aetitle-pairs: #called AE Title - calling AE Title - study wait time (milliseconds)
        SCP:
            SCU: 10000
        test:
            SCU: 60000
            test: 180000
management:
    endpoints:
        web:
            exposure:
                include: "*"
#    server:
#        port: 8080
#        address: 127.0.0.1
