storescp:
    device-name: testscp
    port: 11118
    storage-dir: delete/storescp #set to /temp after testing
    study-wait-time: 30000 #milliseconds, set to 10 min after testing
    clear-storage-directory-on-start: true #warning - will delete all contents of storage directory
    storage-bucket: my-test-bucket
    storage-bucket-region: us-east-1
#Todo: add accepted AE Titles